# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 710)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 710))
        MainWindow.setMaximumSize(QtCore.QSize(1150, 710))
        MainWindow.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_noturno = QtWidgets.QRadioButton(self.centralwidget)
        self.botao_noturno.setGeometry(QtCore.QRect(150, 660, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botao_noturno.setFont(font)
        self.botao_noturno.setObjectName("botao_noturno")
        self.botao_normal = QtWidgets.QRadioButton(self.centralwidget)
        self.botao_normal.setGeometry(QtCore.QRect(70, 660, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botao_normal.setFont(font)
        self.botao_normal.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.botao_normal.setChecked(True)
        self.botao_normal.setObjectName("botao_normal")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 660, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 550, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 550, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: rgb(85, 170, 0);\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #8DC655;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 600, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 0, 0);\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #FF5555;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 200, 61, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.listWidget.setObjectName("listWidget")
        self.botao2 = QtWidgets.QLineEdit(self.centralwidget)
        self.botao2.setGeometry(QtCore.QRect(520, 600, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.botao2.setFont(font)
        self.botao2.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.botao2.setObjectName("botao2")
        self.atividades = QtWidgets.QListWidget(self.centralwidget)
        self.atividades.setGeometry(QtCore.QRect(100, 200, 471, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.atividades.setFont(font)
        self.atividades.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.atividades.setObjectName("atividades")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_error = QtWidgets.QFrame(self.centralwidget)
        self.frame_error.setGeometry(QtCore.QRect(40, 0, 1071, 31))
        self.frame_error.setStyleSheet("background-color: #FF0000;\n"
"border-radius: 5px;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setGeometry(QtCore.QRect(20, 0, 1071, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_error.setFont(font)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.botao_x = QtWidgets.QPushButton(self.frame_error)
        self.botao_x.setGeometry(QtCore.QRect(1040, 6, 16, 16))
        self.botao_x.setStyleSheet("QPushButton{\n"
"    background-image: url(:/btnx_rc/img/cil-x.png);\n"
"    background-repeat: no-repeat;\n"
"    background-color: #731923;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #875F64;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #4C1017\n"
"}")
        self.botao_x.setText("")
        self.botao_x.setObjectName("botao_x")
        self.fundo_top = QtWidgets.QFrame(self.centralwidget)
        self.fundo_top.setGeometry(QtCore.QRect(0, 0, 1151, 161))
        self.fundo_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fundo_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo_top.setObjectName("fundo_top")
        self.frame = QtWidgets.QFrame(self.fundo_top)
        self.frame.setGeometry(QtCore.QRect(200, 20, 751, 161))
        self.frame.setStyleSheet("background-image: url(:/logoos_rc/img/logoos2.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_welcome = QtWidgets.QLabel(self.fundo_top)
        self.label_welcome.setGeometry(QtCore.QRect(20, 135, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_welcome.setFont(font)
        self.label_welcome.setObjectName("label_welcome")
        self.btn_sair = QtWidgets.QPushButton(self.fundo_top)
        self.btn_sair.setGeometry(QtCore.QRect(1030, 130, 61, 31))
        self.btn_sair.setStyleSheet("QPushButton:hover{\n"
"color: #585858;\n"
"}")
        self.btn_sair.setObjectName("btn_sair")
        self.fundo_footer = QtWidgets.QFrame(self.centralwidget)
        self.fundo_footer.setGeometry(QtCore.QRect(0, 659, 1151, 41))
        self.fundo_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fundo_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo_footer.setObjectName("fundo_footer")
        self.label_contato = QtWidgets.QLabel(self.fundo_footer)
        self.label_contato.setGeometry(QtCore.QRect(870, 5, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_contato.setFont(font)
        self.label_contato.setObjectName("label_contato")
        self.ospronta = QtWidgets.QListWidget(self.centralwidget)
        self.ospronta.setGeometry(QtCore.QRect(670, 200, 461, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ospronta.setFont(font)
        self.ospronta.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.ospronta.setObjectName("ospronta")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnlimparatividadesok = QtWidgets.QPushButton(self.centralwidget)
        self.btnlimparatividadesok.setGeometry(QtCore.QRect(670, 550, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnlimparatividadesok.setFont(font)
        self.btnlimparatividadesok.setStyleSheet("QPushButton{\n"
"    background: rgb(255, 0, 0);\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #FF5555;\n"
"}")
        self.btnlimparatividadesok.setObjectName("btnlimparatividadesok")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.n_ospronta = QtWidgets.QListWidget(self.centralwidget)
        self.n_ospronta.setGeometry(QtCore.QRect(590, 200, 61, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.n_ospronta.setFont(font)
        self.n_ospronta.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.n_ospronta.setObjectName("n_ospronta")
        self.btn_excluiros = QtWidgets.QPushButton(self.centralwidget)
        self.btn_excluiros.setGeometry(QtCore.QRect(100, 600, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_excluiros.setFont(font)
        self.btn_excluiros.setStyleSheet("QPushButton{\n"
"    background: #bd1515;\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #B15B5F;\n"
"}")
        self.btn_excluiros.setObjectName("btn_excluiros")
        self.btn_excluiros_n = QtWidgets.QLineEdit(self.centralwidget)
        self.btn_excluiros_n.setGeometry(QtCore.QRect(280, 600, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_excluiros_n.setFont(font)
        self.btn_excluiros_n.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.btn_excluiros_n.setObjectName("btn_excluiros_n")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 170, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.totalpendencia = QtWidgets.QListWidget(self.centralwidget)
        self.totalpendencia.setGeometry(QtCore.QRect(280, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalpendencia.setFont(font)
        self.totalpendencia.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.totalpendencia.setObjectName("totalpendencia")
        self.totalfinalizadas = QtWidgets.QListWidget(self.centralwidget)
        self.totalfinalizadas.setGeometry(QtCore.QRect(850, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalfinalizadas.setFont(font)
        self.totalfinalizadas.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid black;")
        self.totalfinalizadas.setObjectName("totalfinalizadas")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(750, 170, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_login = QtWidgets.QFrame(self.centralwidget)
        self.frame_login.setGeometry(QtCore.QRect(0, -10, 1171, 711))
        self.frame_login.setStyleSheet("background-color: #121b43;")
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.entrada_senha = QtWidgets.QLineEdit(self.frame_login)
        self.entrada_senha.setGeometry(QtCore.QRect(460, 360, 231, 41))
        self.entrada_senha.setStyleSheet("QLineEdit{\n"
"    font-size: 15px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    background-color: #1d1a8e;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    font-size: 20px;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #0d2dbd;\n"
"    background-color: #1d1a8e;\n"
"}\n"
"\n"
"")
        self.entrada_senha.setText("")
        self.entrada_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entrada_senha.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.entrada_senha.setObjectName("entrada_senha")
        self.btn_entrarlog = QtWidgets.QPushButton(self.frame_login)
        self.btn_entrarlog.setGeometry(QtCore.QRect(460, 440, 231, 41))
        self.btn_entrarlog.setStyleSheet("QPushButton{\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color: #100d76;\n"
"    font-size: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #242178;\n"
"}")
        self.btn_entrarlog.setObjectName("btn_entrarlog")
        self.entrada_login = QtWidgets.QLineEdit(self.frame_login)
        self.entrada_login.setGeometry(QtCore.QRect(460, 310, 231, 41))
        self.entrada_login.setStyleSheet("QLineEdit{\n"
"    font-size: 15px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    background-color: #1d1a8e;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    font-size: 20px;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #0d2dbd;\n"
"    background-color: #1d1a8e;\n"
"}")
        self.entrada_login.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.entrada_login.setObjectName("entrada_login")
        self.frame_2 = QtWidgets.QFrame(self.frame_login)
        self.frame_2.setGeometry(QtCore.QRect(380, 210, 391, 91))
        self.frame_2.setStyleSheet("image: url(:/logoos_rc/img/logoos2.png);\n"
"background-color: #1351CD;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.fundo_login = QtWidgets.QFrame(self.frame_login)
        self.fundo_login.setGeometry(QtCore.QRect(380, 60, 391, 591))
        self.fundo_login.setStyleSheet("background-color: #1351CD;\n"
"border-radius: 5px;")
        self.fundo_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fundo_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo_login.setObjectName("fundo_login")
        self.checkBox_salvardados = QtWidgets.QCheckBox(self.fundo_login)
        self.checkBox_salvardados.setGeometry(QtCore.QRect(80, 350, 111, 21))
        self.checkBox_salvardados.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"\n"
"QCheckBox::indicator::checked{\n"
"    border: 3px solid #030142;\n"
"    background-color: #231f8a;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color: white;\n"
"}")
        self.checkBox_salvardados.setObjectName("checkBox_salvardados")
        self.btn_esquecisenha = QtWidgets.QPushButton(self.fundo_login)
        self.btn_esquecisenha.setGeometry(QtCore.QRect(80, 420, 231, 41))
        self.btn_esquecisenha.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: #b1afd5;\n"
"}")
        self.btn_esquecisenha.setObjectName("btn_esquecisenha")
        self.frame_7 = QtWidgets.QFrame(self.fundo_login)
        self.frame_7.setGeometry(QtCore.QRect(140, 80, 120, 71))
        self.frame_7.setStyleSheet("image: url(:/logomain_rc/img/logomain.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_3 = QtWidgets.QFrame(self.frame_login)
        self.frame_3.setGeometry(QtCore.QRect(0, 659, 1151, 51))
        self.frame_3.setStyleSheet("background-color:#010411;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_error_login = QtWidgets.QFrame(self.frame_login)
        self.frame_error_login.setGeometry(QtCore.QRect(0, 10, 1151, 41))
        self.frame_error_login.setStyleSheet("background-color: #FF0000;")
        self.frame_error_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error_login.setObjectName("frame_error_login")
        self.label_error_2 = QtWidgets.QLabel(self.frame_error_login)
        self.label_error_2.setGeometry(QtCore.QRect(100, 0, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_error_2.setFont(font)
        self.label_error_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_2.setObjectName("label_error_2")
        self.btn_x_login = QtWidgets.QPushButton(self.frame_error_login)
        self.btn_x_login.setGeometry(QtCore.QRect(934, 10, 31, 23))
        self.btn_x_login.setStyleSheet("QPushButton{\n"
"    image: url(:/btnx_rc/img/cil-x.png);\n"
"    background-repeat: no-repeat;\n"
"    background-color: #731923;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #875F64;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #4C1017\n"
"}\n"
"\n"
"")
        self.btn_x_login.setText("")
        self.btn_x_login.setObjectName("btn_x_login")
        self.frame_esquecisenha = QtWidgets.QFrame(self.frame_login)
        self.frame_esquecisenha.setGeometry(QtCore.QRect(0, 10, 1151, 701))
        self.frame_esquecisenha.setStyleSheet("background-color: #121b43;")
        self.frame_esquecisenha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_esquecisenha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_esquecisenha.setObjectName("frame_esquecisenha")
        self.fundo_esquecisenha = QtWidgets.QFrame(self.frame_esquecisenha)
        self.fundo_esquecisenha.setGeometry(QtCore.QRect(420, 120, 391, 391))
        self.fundo_esquecisenha.setStyleSheet("background-color: #1351CD;\n"
"border-radius: 5px;")
        self.fundo_esquecisenha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fundo_esquecisenha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo_esquecisenha.setObjectName("fundo_esquecisenha")
        self.frame_5 = QtWidgets.QFrame(self.fundo_esquecisenha)
        self.frame_5.setGeometry(QtCore.QRect(0, 60, 391, 111))
        self.frame_5.setStyleSheet("image: url(:/logoos_rc/img/logoos2.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_8 = QtWidgets.QLabel(self.fundo_esquecisenha)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 351, 21))
        self.label_8.setStyleSheet("color: white;\n"
"font-size: 14px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.entrada_email = QtWidgets.QLineEdit(self.fundo_esquecisenha)
        self.entrada_email.setGeometry(QtCore.QRect(80, 240, 231, 41))
        self.entrada_email.setStyleSheet("QLineEdit{\n"
"    font-size: 15px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    background-color: #1d1a8e;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    font-size: 20px;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #0d2dbd;\n"
"    background-color: #1d1a8e;\n"
"}")
        self.entrada_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.entrada_email.setObjectName("entrada_email")
        self.btn_recuperarsenha = QtWidgets.QPushButton(self.fundo_esquecisenha)
        self.btn_recuperarsenha.setGeometry(QtCore.QRect(80, 290, 231, 41))
        self.btn_recuperarsenha.setStyleSheet("QPushButton{\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color: #100d76;\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #242178;\n"
"}")
        self.btn_recuperarsenha.setObjectName("btn_recuperarsenha")
        self.label_9 = QtWidgets.QLabel(self.fundo_esquecisenha)
        self.label_9.setGeometry(QtCore.QRect(20, 181, 351, 20))
        self.label_9.setStyleSheet("color: white;\n"
"font-size: 14px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.fundo_esquecisenha)
        self.label_10.setGeometry(QtCore.QRect(20, 200, 351, 20))
        self.label_10.setStyleSheet("color: white;\n"
"font-size: 14px;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btn_recuperarsenha_2 = QtWidgets.QPushButton(self.fundo_esquecisenha)
        self.btn_recuperarsenha_2.setGeometry(QtCore.QRect(80, 340, 231, 21))
        self.btn_recuperarsenha_2.setStyleSheet("QPushButton{\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color: #100d76;\n"
"    font-size: 10px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #242178;\n"
"}")
        self.btn_recuperarsenha_2.setObjectName("btn_recuperarsenha_2")
        self.frame_6 = QtWidgets.QFrame(self.fundo_esquecisenha)
        self.frame_6.setGeometry(QtCore.QRect(49, 10, 301, 71))
        self.frame_6.setStyleSheet("image: url(:/logomain_rc/img/logomain.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_error_password = QtWidgets.QFrame(self.frame_esquecisenha)
        self.frame_error_password.setGeometry(QtCore.QRect(0, 0, 1151, 41))
        self.frame_error_password.setStyleSheet("")
        self.frame_error_password.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error_password.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error_password.setObjectName("frame_error_password")
        self.label_error_password = QtWidgets.QLabel(self.frame_error_password)
        self.label_error_password.setGeometry(QtCore.QRect(100, 0, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_error_password.setFont(font)
        self.label_error_password.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_password.setObjectName("label_error_password")
        self.btn_x_login_2 = QtWidgets.QPushButton(self.frame_error_password)
        self.btn_x_login_2.setGeometry(QtCore.QRect(934, 10, 31, 23))
        self.btn_x_login_2.setStyleSheet("QPushButton{\n"
"    image: url(:/btnx_rc/img/cil-x.png);\n"
"    background-repeat: no-repeat;\n"
"    background-color: #731923;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #875F64;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #4C1017\n"
"}\n"
"\n"
"")
        self.btn_x_login_2.setText("")
        self.btn_x_login_2.setObjectName("btn_x_login_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_esquecisenha)
        self.frame_4.setGeometry(QtCore.QRect(0, 650, 1151, 51))
        self.frame_4.setStyleSheet("background-color:#010411;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_3.raise_()
        self.fundo_login.raise_()
        self.frame_2.raise_()
        self.entrada_senha.raise_()
        self.entrada_login.raise_()
        self.btn_entrarlog.raise_()
        self.frame_error_login.raise_()
        self.frame_esquecisenha.raise_()
        self.fundo_top.raise_()
        self.fundo_footer.raise_()
        self.botao_noturno.raise_()
        self.botao_normal.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.listWidget.raise_()
        self.botao2.raise_()
        self.atividades.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.frame_error.raise_()
        self.ospronta.raise_()
        self.label_4.raise_()
        self.btnlimparatividadesok.raise_()
        self.label_5.raise_()
        self.n_ospronta.raise_()
        self.btn_excluiros.raise_()
        self.btn_excluiros_n.raise_()
        self.label_6.raise_()
        self.totalpendencia.raise_()
        self.label_7.raise_()
        self.totalfinalizadas.raise_()
        self.frame_login.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerenciador de atividades"))
        self.botao_noturno.setText(_translate("MainWindow", "Escuro"))
        self.botao_normal.setText(_translate("MainWindow", "Claro"))
        self.label.setText(_translate("MainWindow", "Modo:"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "DIGITE A ORDEM DE SERVIÇO"))
        self.pushButton.setText(_translate("MainWindow", "ENVIAR"))
        self.pushButton_2.setText(_translate("MainWindow", "FINALIZAR O.S Nº"))
        self.botao2.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "Número"))
        self.label_3.setText(_translate("MainWindow", "Pendências"))
        self.label_error.setText(_translate("MainWindow", "Error 404"))
        self.label_welcome.setText(_translate("MainWindow", "Seja bem-vindo(a)"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.label_contato.setText(_translate("MainWindow", "contato: gabrielpoppes@outlook.com"))
        self.label_4.setText(_translate("MainWindow", "Finalizadas"))
        self.btnlimparatividadesok.setText(_translate("MainWindow", "LIMPAR ORDEM DE SERVIÇOS CONCLUÍDAS"))
        self.label_5.setText(_translate("MainWindow", "Número"))
        self.btn_excluiros.setText(_translate("MainWindow", "EXCLUIR O.S Nº"))
        self.btn_excluiros_n.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "-   Total"))
        self.label_7.setText(_translate("MainWindow", "-   Total"))
        self.entrada_senha.setPlaceholderText(_translate("MainWindow", "SENHA"))
        self.btn_entrarlog.setText(_translate("MainWindow", "ENTRAR"))
        self.entrada_login.setPlaceholderText(_translate("MainWindow", "LOGIN"))
        self.checkBox_salvardados.setText(_translate("MainWindow", "SALVAR DADOS"))
        self.btn_esquecisenha.setText(_translate("MainWindow", "Esqueci minha senha"))
        self.label_error_2.setText(_translate("MainWindow", "Error 404"))
        self.label_8.setText(_translate("MainWindow", "Para recuperar sua senha digite seu e-mail de cadastro."))
        self.entrada_email.setPlaceholderText(_translate("MainWindow", "E-MAIL"))
        self.btn_recuperarsenha.setText(_translate("MainWindow", "RECUPERAR SENHA"))
        self.label_9.setText(_translate("MainWindow", "Será enviado um link na sua caixa de entrada para "))
        self.label_10.setText(_translate("MainWindow", "redefinição da senha."))
        self.btn_recuperarsenha_2.setText(_translate("MainWindow", "VOLTAR A TELA INICIAL"))
        self.label_error_password.setText(_translate("MainWindow", "Error 404"))
import botaoclose_rc
import botaologin_rc
import logoprincipal_rc
import logotipo_rc
